name: nine_scaling_image
description: An extended Image widget with nine-scaling
version: 1.0.1
homepage: https://github.com/mikanbox/nine_scaling_image

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pub_semver: ^2.1.4

flutter: